# -*- coding: utf-8 -*-
"""Mlops Major final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10_Y34bZMaKo6ZvAsPHVFg1H0Knvpwz3Z

Q1 Question 1: Data Structure and Processing Pipeline (15
marks)
"""

from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
iris_data=load_iris()
X=iris_data.data
y=iris_data.target
feature_names=iris_data.feature_names
target_names=iris_data.target_names
df=pd.DataFrame(X,columns=feature_names)
df['target']=y
df.head()

numerical_pipeline=Pipeline([('StandardScaler',StandardScaler())])
df[feature_names] = numerical_pipeline.fit_transform(df[feature_names])
df.head()

from sklearn.model_selection import train_test_split
X=df[feature_names]
y=df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)

X_train